version: '3'

networks:
  mtr:
    driver: bridge

services:
  node:
    restart: always
    container_name: mtr-engine
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - mtr
  cron:
    image: php:7.4-apache
    container_name: mtr-cron
    links:
      - node
    networks:
      - mtr
